// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhsboffiiylfiqakjkri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impoc2JvZmZpaXlsZmlxYWtqa3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjgwMzQsImV4cCI6MjA2NzgwNDAzNH0.PLh47A1YWOgu48oPNmYT4I0P8FBrSWw1xXiqCH1fQBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});